### ISSUE TITLE
Predict in ctc & attention model 

### ISSUE THREAD

**Issue by vipcualo** [ray075hl/attention-ocr-toy-example#10]
Thanks you for share code !
In Ctc & attention model, i don't know which model you use for  Inference time ( you use ctc or attention model ) ?
Can you help me. Thanks !

**Comment by ray075hl** [comment]
Hello @vipcualo ! This project do not have inference code. Joint CTC to accelerate the coverage speed of attention model is my original purpose. So I will choose attention model as evaluated model. 
But both of them will output the ocr result.

**Comment by vipcualo** [comment]
hello @ray075hl , if you choose attention model as evaluated model, why you choose ctc_loss_weights = 0.8 ( default in your code ) ?, It seems a bit biased for the ctc modem. 
And have you ever compared between attention model without CTC and attention model ( join ctc ) about accuracy ?

**Comment by ray075hl** [comment]
Hi @vipcualo 
1. Loss weights refrence from [here](https://arxiv.org/pdf/1609.06773v1.pdf) as commited in the code.       https://github.com/ray075hl/attention-ocr-toy-example/blob/f44bb82ba7cac7c11357a7f16e651352732625e1/ctc_joint_attention_model.py#L32
2. Joint ctc have little effect on accuracy.
