### ISSUE TITLE
attention代码的疑问？

### ISSUE THREAD

**Issue by fendaq** [ray075hl/attention-ocr-toy-example#2]
attention 机制应该需要使用encoder的hide states，但是我看代码里enc_state没有返回，decoder也没有用enc_state初始化？这里是不是有问题？

**Comment by ray075hl** [comment]
@fendaq  你好，我理解的是enc_outputs, enc_state = tf.nn.bidirectional_dynamic_rnn(...) 第一个enc_outputs就是hidden state啊， 而 enc_state 则是最后的两个state。

**Comment by fendaq** [comment]
1. outputs为(output_fw, output_bw)，是一个包含前向cell输出tensor和后向cell输出tensor组成的元组。假设
time_major=false,tensor的shape为[batch_size, max_time, depth]。实验中使用tf.concat(outputs, 2)将其拼接。
2. output_states为(output_state_fw, output_state_bw)，包含了前向和后向隐藏状态的组成的元组。

**Comment by ray075hl** [comment]
@fendaq  outputs的shape为[batch_size, max_time, depth]  max_time 是时间轴   每一个时间轴输出一个hidden state  所以我理解 outputs 就是hidden states    不知道我的理解对吗？

**Comment by ray075hl** [comment]
@fendaq output_states 只是最后的state
[https://www.tensorflow.org/api_docs/python/tf/nn/bidirectional_dynamic_rnn](https://www.tensorflow.org/api_docs/python/tf/nn/bidirectional_dynamic_rnn)
output_states: A tuple (output_state_fw, output_state_bw) containing the forward and the backward **_`final`_** states of bidirectional rnn.

**Comment by fendaq** [comment]
我看tensorflow nmt的代码是使用了enc_state 作为 attention 输入的
https://github.com/tensorflow/nmt

**Comment by ray075hl** [comment]
@fendaq  [https://github.com/tensorflow/nmt/blob/master/nmt/model.py](https://github.com/tensorflow/nmt/blob/master/nmt/model.py)  637行   
640行 # We only make use of encoder_outputs in attention-based models
这个代码我没研读过， 不过这注释似乎说是没有用enc_state


如果需要用enc_state， 也只能是用来初始化第一个解码时的z0， 实际上这个z0， 既可以用enc_state来初始化，也可以常量来初始化，个人理解，并没有绝对统一的做法。
你看这里， 
[https://github.com/tensorflow/nmt/blob/58abf51aaf637962b0a5342afcd480af5cda7227/nmt/attention_model.py](https://github.com/tensorflow/nmt/blob/58abf51aaf637962b0a5342afcd480af5cda7227/nmt/attention_model.py) 131~137行 应该能解答你的疑惑了

**Comment by fendaq** [comment]
多谢楼主！
