### ISSUE TITLE
deocde训练阶段的输入

### ISSUE THREAD

**Issue by wushilian** [ray075hl/attention-ocr-toy-example#3]
代码里训练阶段使用TrainingHelper，这样decode的输入就是target，但带来一个问题，就是测试的时候是没有target的，这样训练与测试的环境差的很大。实际我发现，训练阶段准确率很高，但测试的时候准确率很低。所以能不能在训练的时候用decode的输出当做输入？而不是用target当做输入

**Comment by ray075hl** [comment]
@wushilian  用这个函数 ScheduledEmbeddingTrainingHelper 就可以
train_helper = tf.contrib.seq2seq.ScheduledEmbeddingTrainingHelper(output_embed,att_train_length,
                      embeddings,sample_rate)
sample_rate 就是 从decode输出中采样的概率 
sample_rate=0 的时候就是全部用groundtruth做输入。
sample_rare=1 的时候就是全部用decode的输出做输入。
我觉得最好把sample_rate 作为一个placeholder  随着training step 的增加而逐渐增加 
这样既可以加速收敛 也能消除你说的这种gap  不知道我的理解对不对

**Comment by wushilian** [comment]
@ray075hl 非常感谢，我先试一下。实际上做实验发现，用PAD作输入也比用target作输入效果好很多。

**Comment by ray075hl** [comment]
@wushilian 类别少的话可以   类别多的话（中文字符）  这么做是很难收敛的

**Comment by LinJM** [comment]
ScheduledEmbeddingTrainingHelper感觉很重要，我也遇到了这个问题，Training阶段loss很快就降到零，可是Testing阶段效果很差。
