### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by peternara** [ray075hl/attention-ocr-toy-example#4]
hi
..
File "../model.py", line 228, in _att_decode
    att_outputs, _. _ = tf.contrib.seq2seq.dynamic_decode( decoder=decoder, output_time_major=False, impute_finished=True, maximum_iterations=self.params.attention_iteration)
..
ValueError: Shape must be rank 1 but is rank 2 for '..../while/BasicDecoderStep/decoder/attention_wrapper/concat' (op: 'ConcatV2') with input shapes: [64], [64,256], [].

do you kow this problem?
thanks.

**Comment by ray075hl** [comment]
which file? Maybe you should try to git pull the latest code. @peternara  
Several days ago I fixed some bugs.

**Comment by peternara** [comment]
thanks.
