### ISSUE TITLE
about ctc & attention model

### ISSUE THREAD

**Issue by peternara** [ray075hl/attention-ocr-toy-example#6]
Hi, @ray075hl 

Have you compared CTC and attention results using ctc&attention model? In the related study,CTC was found to play an auxiliary role. 
but...In actual results, CTC results were better than attention results. Do you have an opinion on this?

ps.
related paper : JOINT CTC-ATTENTION BASED END-TO-END SPEECH RECOGNITION USING MULTI-TASK LEARNING

**Comment by ray075hl** [comment]
Good question!  I have the same question as you.  Theoretically, attention mechanism(AM) self include language model that CTC do not have, the former should be better than latter. When I tested two models to the images with slight noise or without noise,  I got comparable result. So I think the AM is sensitive about noise which leads to misalignment. CTC is more robust in alignment.  I am exploring variants of AM to deal with this problem...

**Comment by peternara** [comment]
thanks for reply.
Then, as compared with the CTC learning model alone, Do you think that the CTC results in a model(jontly ctc & attention model) that has learned both algorithms at the same time should be improved?

In fact, I think I can see it. However, it is ambiguous. :)
In this way of solving the problem of "attention drift" phenomenon, I think that the feature level is  re-expressed(? representation) as a more robust feature that can reduce the phenomenon.

**Comment by ray075hl** [comment]
Really appreciate your suggestions and opinions. 
I will try using densenet to replace common cnn layers.

**Comment by peternara** [comment]
@ray075hl 
Oh, will that open the densenet toy source code? If so, I look forward to it.:)

**Comment by ray075hl** [comment]
Of course， open source code！

**Comment by peternara** [comment]
@ray075hl thanks~:)
