### ISSUE TITLE
关于代码的一些疑问

### ISSUE THREAD

**Issue by wushilian** [ray075hl/attention-ocr-toy-example#7]
tf.contrib.seq2seq.LuongAttention(num_units=cfg.RNN_UNITS, memory=memory)这里的memory是什么意思？我看代码是把encode的输出当作memory的，另外我把tf.contrib.seq2seq.BasicDecoder(
            cell=attn_cell, helper=helper,
            initial_state=attn_cell.zero_state(dtype=tf.float32, batch_size=cfg.BATCH_SIZE).clone(cell_state=enc_state[0]),
            output_layer=output_layer)
里面的state从0改为encode的状态，效果好了很多，这是为什么？

**Comment by ray075hl** [comment]
1.memory 就是 attention 解码时 要挑选的那一堆hidden ouputs（由双向gru产生的）。
2.因为相当于initial_state也参与了训练，bp的时候会考虑initial_state。我在做实验时，会用clone(cell_state=enc_state[1])， enc_state[1]是反向的gru state， 相当于图片头部的一个feature map，另initial_state = enc_state[1]，等于是人为对齐了一次，可以大幅降低第一次解码不正确的情形。但实验中发现使用enc_state[0]，enc_state[1]效果差不多，所以initial_state也参与了训练，才是提升的关键所在。
个人理解  仅供参考

**Comment by LinJM** [comment]
@wushilian 我用了你那份代码做英文识别，发现training的时候，loss降低的很快，但是testing的时候结果比较差

**Comment by wushilian** [comment]
@LinJM 我刚改了一下代码，还在训练，但效果已经比之前好很多了

**Comment by wushilian** [comment]
@ray075hl 还有几个问题：1.输入数据的label是不定长的，是不是要加<pad>到同一长度
2.实验发现，假如把训练数据的label都pad到固定长度比如27，那TrainingHelper里面的seq_len也要是[27]*batch，不然就会报错
3.decode里每个batch的序列长度是不是应该相等？

**Comment by ray075hl** [comment]
其实这些问题是一个问题，为了方便，我的做法是每一个batch的序列长度一致，不同的batch的长度可以变化，做法是把train_length作为一个placeholder传入 。
例如  第一个batch的长度是20   按你的写法   [20]*batch
         第二个batch的长度是27   ........................   [27]*batch
         ................................................................................[train_length]*batch

**Comment by LinJM** [comment]
@ray075hl @wushilian 

![image](https://user-images.githubusercontent.com/5347113/35134599-46a19b2e-fd12-11e7-9d28-e2d9dea3b69d.png)

**Comment by wushilian** [comment]
@LinJM 所以decode应该是要用encode的state来初始化，另外能不能发下论文名字？

**Comment by LinJM** [comment]
@wushilian Bidirectional decoder networks for attention-based end-to-end offline handwriting
recognition

**Comment by ray075hl** [comment]
@LinJM  thanks

**Comment by wushilian** [comment]
@ray075hl 要不建个群交流

**Comment by LinJM** [comment]
@wushilian @ray075hl 我微信号：moco4236，欢迎加我微信~

**Comment by fendaq** [comment]
我用nmt改了一个版本，直接修改nmt  encoder侧的输入，在embed前加入cnn就可以了，其他的基本不需要修改，训练数据从1字到50字随机生成，图片统一为32*1024，测试了一下，中文可以收敛的，但是最后结果效果没有比ctc好。。。
我之前建了一个crnn的群，有兴趣可以加一下： 274634783，这样讨论起来比较方便

**Comment by wushilian** [comment]
@fendaq https://github.com/fendaq/Sequence_to_sequence_with_attention是这个吗

**Comment by fendaq** [comment]
@wushilian https://github.com/tensorflow/nmt
