### ISSUE TITLE
CTC_model feature_length

### ISSUE THREAD

**Issue by peterWon** [ray075hl/attention-ocr-toy-example#8]
您好，请问下CTC_model里面的feature_length为什么是固定的29呢，我替换为实际的label sequence的长度反而会报错。还有就是是否CTC_model的project_out用np.argmax(project_out, axis = 1)就应该是预测的结果？我在训练的时候输出的loss降低的很快，但是按照上述方式解码出来看上去只有少数两三个字符顺序是正确的。
期待您解惑，非常感谢！

**Comment by ray075hl** [comment]
@peterWon  
**第一个问题：关于feature_length和label sequence。**
feature_length 指的是一张图片进过CNN之后的tensor的timestep， 例如训练的输入图片的尺寸固定为32x400x1 经过 所有cnn 之后的形状为[batch_size, 1, 100, 512]  squeeze后的形状为[batch_size, 100, 512]。
那么这个 feature_length 就应该固定为100；
label sequence 的长度是变化的， 它的长度取决于在图片上贴了几个字，3个字那么label sequence就等于3。
**第二个问题：是否CTC_model的project_out用np.argmax(project_out, axis = 1)就应该是预测的结果？**
不是，假设输入图片的形状为32x400x1, 且图片上有5个字,  如果只针对数字识别问题(0~9)，那么project_out的形状为[100，10]， 10代表类别总数。此时np.argmax(project_out, axis = 1)的输出为[100, 1]
而标签(ground truth)为[5,1], 显然不是。       正确的做法是将[100, 1]的向量经过一定的后处理,如去掉重复字符和blank, 这个过程叫做ctc decode。
**第三个问题: 只有少数两三个字符顺序**
这份代码只是一个toy example，主要是关于attention的使用。 如果是针对其他大的数据集， 里面的超参数需要换， 数据生成算法也要变得更加贴合真实数据的分布，如增加噪声，扭曲，仿射变化等等。


个人理解  仅供参考

**Comment by peterWon** [comment]
@ray075hl
非常感谢您的解答！
